// Generated by `wrangler types` — extend as needed.
interface Env {
  DB: D1Database
  VAPID_PUBLIC_KEY: string
  VAPID_PRIVATE_KEY: string
  VAPID_SUBJECT: string   // "mailto:contact@example.com"
  CORS_ORIGIN: string
}
